# -*- coding: utf-8 -*-
"""ConsolidatedRun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VScNIwo_i26seWYCDnIQ2WgY0J1o0NFm
"""

import torch, gc
if 'engine' in locals(): del engine
gc.collect()
torch.cuda.empty_cache()

import sys
# Replace this with the actual folder path you copied
sys.path.append('/content/drive/MyDrive/capstone_project/')

!pip install langchain_huggingface
!pip install chromadb
!pip install -U bitsandbytes>=0.46.1

import os
import json
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor
import torch
import chromadb

# Import core LangChain orchestration tools
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline, BitsAndBytesConfig
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from customer_data_orchestrator import CustomerDataOrchestrator

# Import your consistent multi-layered Pydantic blueprint
from xdm_schema_models import ChurnAnalytics

class RetentionEngine:



    sql_db_path ='/content/drive/MyDrive/capstone_project/storage/capstone.db'
    chroma_path = "/content/drive/MyDrive/capstone_project/storage/chroma_db"

    def __init__(self, model_id: str = "Qwen/Qwen2.5-7B-Instruct"):
        """
        Constructor executes EXACTLY ONCE per application lifecycle.
        Loads the model and tokenizer onto the GPU memory and locks it in.
        """
        print(f"🚀 Initializing RetentionEngine. Loading {model_id} onto GPU VRAM...")
        self.model_id = model_id

        # 1. Infrastructure Infrastructure Configuration
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)

        quant_config = BitsAndBytesConfig(
            load_in_8bit=True
        )

        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_id,
            quantization_config=quant_config,
            device_map="auto",
            torch_dtype=torch.float16
        )

        # 2. Wrap LangChain Pipeline Elements
        hf_pipeline = pipeline(
            "text-generation",
            model=self.model,
            tokenizer=self.tokenizer,
            max_new_tokens=512,
            max_length=None,
            temperature=0.1,
            do_sample=True,
            return_full_text=False  # Crucial: Isolates LLM tokens from prompt history
        )
        llm = HuggingFacePipeline(pipeline=hf_pipeline)
        self.chat_model = ChatHuggingFace(llm=llm)

        # 3. Setup Parsers & Prompts
        self.parser = PydanticOutputParser(pydantic_object=ChurnAnalytics)

        self.prompt_template = ChatPromptTemplate.from_messages([
            ("system", (
                "You are an elite automated AI customer retention engine operating on enterprise data feeds.\n"
                "Your task is to analyze the customer record - profile, events, support tickets and the customer review and generate an operational assessment.\n\n"
                "{format_instructions}\n\n"
                "Crucial Directive: Do not include any conversational greetings, explanations, introduction filler, "
                "or markdown code fences (like ```json). Your response must be an instantly checkable raw text JSON structure."
            )),
            ("user", "Analyze this customer data profile context: {customer_data_json}")
        ])

        # 4. Lock down the native LCEL Chain
        self.retention_pipeline_chain = self.prompt_template | self.chat_model | self.parser
        print("✅ RetentionEngine successfully instantiated and resident in VRAM.")

    def build_aep_xdm_envelope(self, customer_id: str, profile_data: dict, llm_insights: dict, iso_now: str) -> dict:
        """Deterministic Factory mapping analytical results to static Adobe XDM Schema Layouts."""
        return {
            "header": {
                "schemaRef": "https://adobe.com",
                "imsOrgId": "YOUR_IMS_ORG_ID@AdobeOrg"
            },
            "_id": f"evt-{customer_id}-{iso_now.replace(':', '-')}",
            "timestamp": iso_now,
            "endUserIDs": {
                "_experience": {
                    "crmID": {"id": customer_id, "namespace": {"code": "CRM_ID"}}
                }
            },
            "_your_tenant": {
                "churnAnalytics": {
                    "churnRiskLevel": llm_insights.get("churnRiskLevel"),
                    "sentimentLabel": llm_insights.get("sentimentLabel"),
                    "primaryDriver": llm_insights.get("primaryDriver"),
                    "llmReasoningSummary": llm_insights.get("llmReasoningSummary")
                },
                "auditTrail": {
                    "processedTimestamp": iso_now,
                    "modelUsed": self.model_id
                }
            }
        }

    def run_retention_inference(self, customer_id: str, data_orchestrator: CustomerDataOrchestrator) -> dict:
        """Runs inference for a single target profile against the loaded in-memory model."""
        print(f"⚡ Thread worker processing record: {customer_id}")

        try:


            print("Start - Chain Invoke Command")
            # Step A: Compile footprint from DB files
            data_context = data_orchestrator.get_clean_customer_story(customer_id)
            print(f"customer_data_json : {json.dumps(data_context)}")


            iso_now = datetime.utcnow().isoformat() + "Z"

            print(f"format_instructions : {self.parser.get_format_instructions()}")


            # Step B: Direct invocation over the native chain
            validated_xdm_payload = self.retention_pipeline_chain.invoke({
                "format_instructions": self.parser.get_format_instructions(),
                "customer_data_json": json.dumps(data_context)
            })

            print(f"validated xdm payload : {validated_xdm_payload.dict()}")

            llm_insights = validated_xdm_payload.dict()

            # Step C: Formulate full static AJO envelope
            final_aep_payload = self.build_aep_xdm_envelope(
                customer_id=customer_id,
                profile_data=data_context.get("profile", {}),
                llm_insights=llm_insights,
                iso_now=iso_now
            )

            print(f"final xdm payload : {final_aep_payload}")

            return {
                "customer_id": customer_id,
                "status": "Success",
                "error_log": None,
                "xdm_payload": final_aep_payload
            }

        except Exception as validation_error:
            print(f"⚠️ Validation Failure or Missing fields on {customer_id}!")
            return {
                "customer_id": customer_id,
                "status": "Failed JSON Validation Schema",
                "error_log": str(validation_error),
                "xdm_payload": None
            }

    def run_batch_processing(self, customer_ids: list, data_orchestrator: CustomerDataOrchestrator, output_dir: str = "./aep_payloads", max_workers: int = 4):
        """
        Orchestrates multi-threaded profile execution using a dedicated ThreadPoolExecutor.
        Saves each successful XDM payload cleanly to disk as a JSON artifact.
        """
        os.makedirs(output_dir, exist_ok=True)
        results_summary = []

        print(f"📦 Launching ThreadPoolExecutor (max_workers={max_workers}) for {len(customer_ids)} profiles...")

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            # Submit all execution workflows to the thread pool worker queues
            futures = [
                executor.submit(self.run_retention_inference, cid, data_orchestrator)
                for cid in customer_ids
            ]

            # Gather and write results as they complete processing loops
            for idx, future in enumerate(futures):
                result = future.result()
                customer_id = result["customer_id"]

                if result["status"] == "Success":
                    file_path = os.path.join(output_dir, f"{customer_id}_xdm.json")
                    with open(file_path, "w") as f:
                        json.dump(result["xdm_payload"], f, indent=2)

                    print(f"✅ [{idx+1}/{len(customer_ids)}] Saved payload file: {file_path}")
                    results_summary.append({"customer_id": customer_id, "status": "Saved"})
                else:
                    print(f"❌ [{idx+1}/{len(customer_ids)}] Failed profile processing on {customer_id}.")
                    results_summary.append({"customer_id": customer_id, "status": "Failed", "error": result["error_log"]})

        return results_summary

# 1. Initialize your DB drivers once at the root level
sql_db_path = "/content/drive/MyDrive/capstone_project/storage/capstone.db"
chroma_path = "/content/drive/MyDrive/capstone_project/storage/chroma_db"
shared_orchestrator = CustomerDataOrchestrator(sql_db_path, chroma_path)

# 2. Instantiate the engine once (Locks model to VRAM)
engine = RetentionEngine(model_id="Qwen/Qwen2.5-7B-Instruct")

# 3. Create your input workload target list
#target_customers = ["CUST-191", "CUST-192", "CUST-193", "CUST-194", "CUST-195"]
#target_customers = ["CUST-191"]
conn = sqlite3.connect(sql_db_path)
cursor = conn.cursor()

action = "Checkout Success"
cursor.execute("SELECT DISTINCT customer_id FROM events WHERE action = ?", (action,))
raw_rows = cursor.fetchall()

# ⚡ CRUCIAL: Extract the first element [0] out of each tuple to build a clean string list
target_customers = [row[0] for row in raw_rows]

conn.close()

# 4. Trigger the thread pool batch run
batch_log = engine.run_batch_processing(
    customer_ids=target_customers,
    data_orchestrator=shared_orchestrator,
    output_dir="/content/drive/MyDrive/capstone_project/aep_payloads",
    max_workers=4  # ⚡ Controlled concurrency limit
)



