# -*- coding: utf-8 -*-
"""Audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yY21aA5SBXiTXIitSwL5kgPXQZuae01E
"""

import torch
import gc

print("🧹 Initializing GPU memory purge protocol...")

# 1. Delete your primary inference engine variables from scope
if 'engine' in locals():
    del engine
if 'retention_pipeline_chain' in locals():
    del retention_pipeline_chain
if 'chat_model' in locals():
    del chat_model
if 'model' in locals():
    del model

# 2. Force Python to run garbage collection on CPU memory bindings
gc.collect()

# 3. Explicitly purge VRAM allocations off the graphics card hardware
torch.cuda.empty_cache()

print("✅ GPU Memory successfully cleared. Ready to safely initialize your Gemma 4 Judge model layer!")

import os
import json
import sys
import torch

# Add the directory containing 'customer_data_orchestrator.py' to the Python path
sys.path.insert(0, '/content/drive/MyDrive/capstone_project/')

!pip install langchain_huggingface
!pip install chromadb
!pip install -U bitsandbytes>=0.46.1
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline, BitsAndBytesConfig
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from customer_data_orchestrator import CustomerDataOrchestrator

class OpenSourceAuditEngine:
    def __init__(self, model_id: str = "google/gemma-4-12b-it"):
        """Loads your quantized Gemma 4 12B auditor layer."""
        print(f"🕵️‍♂️ Initializing Uncoupled Auditor Layer: {model_id}...")
        self.model_id = model_id
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)

          # 1. ⚡ CONFIGURE STRICT 4-BIT INFRASTRUCTURE GUARDRAILS
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",           # NF4 is highly optimized for performance retention
            bnb_4bit_compute_dtype=torch.float16, # Math calculations execute in fast 16-bit float
            bnb_4bit_use_double_quant=True       # Extra compression layer to save maximum memory
        )

        # 2. Pass the configuration wrapper into the weight loader
        self.model = AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=quant_config,
            device_map="auto",
            torch_dtype=torch.float16
        )

        hf_pipeline = pipeline(
            "text-generation",
            model=self.model,
            tokenizer=self.tokenizer,
            max_new_tokens=256,
            temperature=0.0,  # Force absolute determinism for grading matrix
            do_sample=False,
            return_full_text=False
        )
        self.chat_model = ChatHuggingFace(llm=HuggingFacePipeline(pipeline=hf_pipeline))
        self.parser = JsonOutputParser()

        # 🔮 OPTIMIZED PROMPT: Evaluates pure source data vs pure model extraction
        self.prompt_template = ChatPromptTemplate.from_messages([
            ("system", (
                "You are an expert Enterprise AI Compliance Auditor verifying customer analytics data accuracy.\n"
                "You will be given a raw customer story context (database inputs) and the analytical insights extracted by an operational system.\n\n"
                "Your task is to independently cross-examine the extraction for logic gaps, timeline tracking, and hallucination.\n\n"

                "CRITICAL SCORING RUBRICS:\n"
                "1. Accuracy (1-5): Does the 'llmReasoningSummary' perfectly ground itself in the raw text inputs?\n"
                "   - 5: Every single claim in the summary matches the raw text exactly with zero additions.\n"
                "   - 3: The summary is mostly true but adds mild extrapolation or vague inferences not in the text.\n"
                "   - 1: The summary claims events, timelines, or issues that are completely absent or false.\n\n"

                "2. Relevance (1-5): Does the 'churnRiskLevel' and 'sentimentLabel' match the human emotional tone and operational timeline details included under 'support_tickets' and/or 'customer_reviews'?\n"
                "   - 5: Flawless alignment. High anger matches HIGH risk; minor queries match LOW risk.\n"
                "   - 3: Minor logical mismatch. (e.g., A customer expresses 'extreme frustration' but is marked as MEDIUM risk solely due to a strict SLA timeline rule).\n"
                "   - 1: Gross contradiction. (e.g., Customer shares a fully delighted review but is marked as HIGH churn risk with zero open issues).\n\n"

                "Return a raw, flat JSON instance containing ONLY these exact root-level keys:\n"
                "- accuracy_score: (integer from 1 to 5)\n"
                "- relevance_score: (integer from 1 to 5)\n"
                "- judge_rationale: (a concise, 1-sentence explanation focusing precisely on alignments or drifts)\n\n"
                "Crucial Directive: You must output ONLY raw, valid JSON. "
                "Do not include any markdown code fences (like ```json), HTML-like tags, "
                "or internal system tags (such as <channel|>, <turn|>, or the word 'thought'). "
                # FIX: Doubled the curly braces below so LangChain treats them as literal characters
                "Your response must start exactly with '{{' and end exactly with '}}'."
            )),
            ("user", (
                "### RAW CUSTOMER STORY CONTEXT (INPUT):\n"
                "{raw_customer_context_json}\n\n"
                "### GENERATED INSIGHT DATA (OUTPUT TO AUDIT):\n"
                "{extracted_insights_json}"
            ))
        ])



        self.audit_chain = self.prompt_template | self.chat_model | self.parser
        print("✅ Auditor Judge Engine successfully loaded with clean-token context mapping.")

    def execute_cross_validation_audit(self, payloads_dir, data_orchestrator):
        """
        Iterates through files, extracts ONLY the insights block, grabs fresh DB context,
        and cross-validates them efficiently.
        """
        self.audit_results = []
        files_to_audit = [f for f in os.listdir(payloads_dir) if f.endswith("_xdm.json")]

        print(f"📊 Commencing cross-validation audit loop over {len(files_to_audit)} files...")

        for idx, filename in enumerate(files_to_audit):
            file_path = os.path.join(payloads_dir, filename)
            customer_id = filename.replace("_xdm.json", "")

            # 1. Read file and peel away static Adobe metadata to save tokens
            with open(file_path, "r") as f:
                full_xdm_payload = json.load(f)

            # Extract ONLY the target metrics block
            extracted_insights = full_xdm_payload.get("_your_tenant", {}).get("churnAnalytics", {})
            print(f"extracted insights : {extracted_insights}")

            # 2. Pull the exact same raw data query that Qwen used
            raw_customer_context = data_orchestrator.get_clean_customer_story(customer_id)
            print(f"raw customer context : {raw_customer_context}")

            try:
                # 3. Fire the audit check passing clean, lightweight token footprints
                evaluation = self.audit_chain.invoke({
                    "raw_customer_context_json": json.dumps(raw_customer_context),
                    "extracted_insights_json": json.dumps(extracted_insights)
                })

                print(f"evaluation wo customer id : {evaluation}")

                evaluation["customer_id"] = customer_id
                print(f"evaluation with customer id : {evaluation}")
                self.audit_results.append(evaluation)
                print(f"✅ [{idx+1}/{len(files_to_audit)}] Audited {customer_id} -> Accuracy: {evaluation.get('accuracy_score')}/5")

            except Exception as e:
                print(f"❌ [{idx+1}/{len(files_to_audit)}] Failed to audit file {filename}: {e}")

        return self.audit_results

auditor = OpenSourceAuditEngine()

import json
import os

sql_db_path = "/content/drive/MyDrive/capstone_project/storage/capstone.db"
chroma_path = "/content/drive/MyDrive/capstone_project/storage/chroma_db"
summary_file_path = "/content/drive/MyDrive/capstone_project/storage/audit_results_summary.json"

shared_orchestrator = CustomerDataOrchestrator(sql_db_path, chroma_path)
audit_logs = []

# 1. Run the audit pipeline
try:
    # Direct assignment since the function returns the list
    audit_logs = auditor.execute_cross_validation_audit(
        payloads_dir="/content/drive/MyDrive/capstone_project/aep_payloads",
        data_orchestrator=shared_orchestrator,
    )
except Exception as main_error:
    print(f"\n💥 Pipeline broke: {main_error}")
    # Rescue the partial data from the auditor's internal state
    audit_logs = getattr(auditor, "audit_results", [])

# 2. Print whatever is in the list right now
print("\n--- 📝 CURRENT AUDIT LOGS IN LIST ---")
print(f"Total records found: {len(audit_logs)}")
print(json.dumps(audit_logs, indent=2, ensure_ascii=False))
print("------------------------------------\n")

# 3. Save the results
if audit_logs:
    os.makedirs(os.path.dirname(summary_file_path), exist_ok=True)
    with open(summary_file_path, "w") as f:
        json.dump(audit_logs, f, indent=2, ensure_ascii=False)
    print(f"✅ Successfully saved to: {summary_file_path}")
else:
    print("❌ List is empty. Nothing to save.")